### ISSUE TITLE
meta tags in blog posts

### ISSUE THREAD

**Issue by j-mplourde** [karlb/karl.berlin#1]
Is it possible to add meta tags to a blog post generated html? I'd like to add twitter meta tags so my post links generate a preview.

Thank you!

**Comment by karlb** [comment]
You can add arbitrary HTML to your posts, but if you close the HTML head in your header.html (which I would expect), these tags will  show up in the body, which to my knowledge violates the HTML spec.

So I don't think there is a ready made way to to this, but you could modify the `write_page` function to do what you want. I imagine something like
* filter lines that match `<meta.*>` from your blog post
* replace a META_TAGS_HERE marker in your header.html with the filtered lines

**Comment by j-mplourde** [comment]
That is what I figured out, hoping I could have missed something to make it work. 

Thank you for your answer, I will try and hack something.
