### ISSUE TITLE
Invalid markup in `posts/git-default-branch.md`

### ISSUE THREAD

**Issue by linnnus** [karlb/karl.berlin#2]
The branch names in `posts/git-default-branch.md` use `` `foo' ``-style quotes around the different branch names. `smu` misinterpretes these. I believe the intended use is either `` `foo` ``-style quotes, `` \`foo' ``, or `` 'foo' ``-style quotes.

**Comment by karlb** [comment]
I used a too smart spell checker which messed up the quotes. Won't do that again. I hope I fixed all bad cases now in https://github.com/karlb/karl.berlin/commit/b17399d098c4df594bec391f701fb20e8dc845d0.

Thanks for letting me know!
